version: '3.2'
services:
  test-php:
    depends_on:
      - chrome

  chrome:
    image: selenium/standalone-chromium:134.0
    shm_size: 2gb # recommended by seleniumhq https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#--shm-size2g
    ports:
      - '4444'
      - '5900'
    environment:
      - SE_VNC_NO_PASSWORD=1

  firefox:
    # update to version 3 blocked by https://github.com/facebook/php-webdriver/issues/469
    image: selenium/standalone-firefox-debug:2.53.1
    # workaround for Docker Beta, see https://github.com/SeleniumHQ/docker-selenium/issues/227#issuecomment-224865735
    dns: 8.8.4.4
    environment:
      - no_proxy=localhost
    ports:
      - '4444'
      - '5900'
    volumes:
      # Mount shm, see https://github.com/SeleniumHQ/docker-selenium#running-the-images
      - /dev/shm:/dev/shm
